### ISSUE TITLE
lw18.2

### ISSUE THREAD

**Issue by Andrey540** [MUKIVA/BOP#2]
- [x] Нет контроля на максимальное и минимальное значение
- [x] При копировании имени в файл нужно маркер конца строки также добавлять

**Comment by MUKIVA** [comment]
Поправил

**Comment by Andrey540** [comment]
- [ ] `Score = 0 .. 100;` и `(ScoreValidation >= 0) AND (ScoreValidation <= 100)` используй константы

**Comment by MUKIVA** [comment]
Поправил
