### ISSUE TITLE
lw19.1

### ISSUE THREAD

**Issue by Andrey540** [MUKIVA/BOP#3]
- [x] Программ должна работать следующим образом. Она обрабатывает множество, удаляя из него простые числа. После этого это множество она должна вывести на экран
- [x] `CurrentNumber <= MaxNum` Необязательно все элементы перебирать, достаточно до корня квадратного от Max
- [x] Сейчас шаг поиска = 1 `DelNum := DelNum + 1`  Если рассматривать 2, то удаляются элемнеты 4 6 8, если 3, то 6 9 12. Нужно оптимизировать

**Comment by MUKIVA** [comment]
> Программ должна работать следующим образом. Она обрабатывает множество, удаляя из него простые числа. После этого это множество она должна вывести на экран

По заданию мы должны в итоге вывести множество простых чисел, а в вашем примере мы выводим все не простые числа.
Принимается, что минимальное простое число равно 2. В «решето» помещают все числа в заданном диапазоне. Минимальное число в диапазоне считается простым. Далее оно удаляется из решета и удаляются все ему кратные. Новое минимальное число в диапазоне также является простым. 
Процесс повторяется, пока не будет достигнуто максимальное число в диапазоне.

> CurrentNumber <= MaxNum Необязательно все элементы перебирать, достаточно до корня квадратного от Max

Не понимаю, почему до корня квадратного. Так мы проверим множество от 2 до 10, а нужно до 100. При этом мы не знаем как получить корень т.к. функцию sqrt() нам не давали. И если мы возьмем за Max 10, то мы никогда не достигнем максимального числа в диапазоне, а по заданию нужно дойти именно до 100.

**Comment by MUKIVA** [comment]
> Сейчас шаг поиска = 1 DelNum := DelNum + 1 Если рассматривать 2, то удаляются элемнеты 4 6 8, если 3, то 6 9 12. Нужно оптимизировать

`               BunchOfNumber := BunchOfNumber - [DelNum];
             DelNum := DelNum + CurrentNumber`
Оптимизировал

**Comment by MUKIVA** [comment]
Еще я добавил версию со всеми шагами.

**Comment by Andrey540** [comment]
- в пункте 1 я опечатался, нужно удалять составные.
- если обрабатывать все значения, до тех пор пока не будет пустое множество, то в этом случае алгоритм работает не оптимально.
-не обязательно использовать функцию sqrt для того, чтобы определить больше ли корень квадратный от MaxNum чем CurrentNumber

**Comment by Andrey540** [comment]
- [ ] `DelNum := 2;` и `CurrentNumber := 2;` используй константы
- [ ] `CurrentNumber <= 10` об этом я писал выше

**Comment by MUKIVA** [comment]
Поправил
