### ISSUE TITLE
 РГР

### ISSUE THREAD

**Issue by sokolnikovalexey** [MUKIVA/BOP#6]
Не удалось запустить задание
Функция GET не определена
WordType.pas -> GET(FIn)

Вопрос 2:
  LowerRusChar = ['�' .. '�'];
  UpperRusChar = ['�' .. '�'];
  UpperLatChar = ['A' .. 'Z'];
  LowerLatChar = ['a' .. 'z'];
Вот это можно оформить красивее

**Comment by MUKIVA** [comment]
LowerRusChar = ['�' .. '�'];
UpperRusChar = ['�' .. '�'];
UpperLatChar = ['A' .. 'Z'];
LowerLatChar = ['a' .. 'z'];

Я так понял можно перенести константы в отдельный модуль и записать их следующим образом:
LowerChar = ['а' .. 'я', 'a' .. 'z', 'ё'];
UpperChar = ['А' .. 'Я', 'A' .. 'Z', 'Ё'];
ValidCharSet = LowerChar + UpperChar;
